apiVersion: v1
kind: Pod
metadata:
  labels:
    app: milvus-deploy-test
  namespace: jenkins
spec:
  enableServiceLinks: false
  containers:
  - name: main
    image: milvusdb/pytest:20211209-cef343f
        securityContext:
      privileged: true
    resources:
      limits:
        cpu: "6"
        memory: 12Gi
      requests:
        cpu: "2"
        memory: 10Gi
