apiVersion: v1
kind: Pod
metadata:
  labels:
    app: milvus-deploy-test
spec:
  enableServiceLinks: false
  containers:
  - name: main
    image: milvusdb/krte:20210722-806d13f
    env:
    - name: DOCKER_IN_DOCKER_ENABLED
      value: "true"
    - name: DOCKER_VOLUME_DIRECTORY
      value: "/mnt/disk/.docker"
    - name: KRTE_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    securityContext:
      privileged: true
    tty: true
    args: ["cat"]
    volumeMounts:
    - mountPath: /docker-graph
      name: docker-graph
    - mountPath: /var/lib/docker
      name: docker-root
    - mountPath: /lib/modules
      name: modules
      readOnly: true
    - mountPath: /sys/fs/cgroup
      name: cgroup
    - mountPath: /mnt/disk/.docker
      name: build-cache
      subPath: docker-volume
    - mountPath: /ci-logs
      name: ci-logs  
  volumes:
  - emptyDir: {}
    name: docker-graph
  - emptyDir: {}
    name: docker-root
  - hostPath:
      path: /tmp/krte/cache
      type: DirectoryOrCreate
    name: build-cache
  - hostPath:
      path: /lib/modules
      type: Directory
    name: modules
  - hostPath:
      path: /sys/fs/cgroup
      type: Directory
    name: cgroup
  - name: ci-logs
    nfs:
      path: /volume1/ci-logs
      server: 192.168.1.126